apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <NAMESPACE>
generatorOptions:
  disableNameSuffixHash: true
resources:
  - github.com/ansible/awx-operator/config/default?ref=<OPERATOR_VERSION>
images:
  - name: quay.io/ansible/awx-operator
    newTag: <OPERATOR_VERSION>
